
package com.docusign.hackathon.connect.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "APIServiceSoap", targetNamespace = "http://www.docusign.net/API/3.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APIServiceSoap {


    /**
     * 
     * @param envelope
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateEnvelope", action = "http://www.docusign.net/API/3.0/CreateEnvelope")
    @WebResult(name = "CreateEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateEnvelope")
    @ResponseWrapper(localName = "CreateEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateEnvelopeResponse")
    public EnvelopeStatus createEnvelope(
        @WebParam(name = "Envelope", targetNamespace = "http://www.docusign.net/API/3.0")
        Envelope envelope);

    /**
     * 
     * @param envelope
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateAndSendEnvelope", action = "http://www.docusign.net/API/3.0/CreateAndSendEnvelope")
    @WebResult(name = "CreateAndSendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateAndSendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateAndSendEnvelope")
    @ResponseWrapper(localName = "CreateAndSendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateAndSendEnvelopeResponse")
    public EnvelopeStatus createAndSendEnvelope(
        @WebParam(name = "Envelope", targetNamespace = "http://www.docusign.net/API/3.0")
        Envelope envelope);

    /**
     * 
     * @param accountId
     * @param envelopeId
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "SendEnvelope", action = "http://www.docusign.net/API/3.0/SendEnvelope")
    @WebResult(name = "SendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SendEnvelope")
    @ResponseWrapper(localName = "SendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SendEnvelopeResponse")
    public EnvelopeStatus sendEnvelope(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId,
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId);

    /**
     * 
     * @param correction
     * @return
     *     returns com.docusign.hackathon.connect.model.CorrectionStatus
     */
    @WebMethod(operationName = "CorrectAndResendEnvelope", action = "http://www.docusign.net/API/3.0/CorrectAndResendEnvelope")
    @WebResult(name = "CorrectAndResendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CorrectAndResendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CorrectAndResendEnvelope")
    @ResponseWrapper(localName = "CorrectAndResendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CorrectAndResendEnvelopeResponse")
    public CorrectionStatus correctAndResendEnvelope(
        @WebParam(name = "Correction", targetNamespace = "http://www.docusign.net/API/3.0")
        Correction correction);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFNoWaterMark", action = "http://www.docusign.net/API/3.0/RequestPDFNoWaterMark")
    @WebResult(name = "RequestPDFNoWaterMarkResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFNoWaterMark", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFNoWaterMark")
    @ResponseWrapper(localName = "RequestPDFNoWaterMarkResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFNoWaterMarkResponse")
    public EnvelopePDF requestPDFNoWaterMark(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @param pdfOptions
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFWithOptions", action = "http://www.docusign.net/API/3.0/RequestPDFWithOptions")
    @WebResult(name = "RequestPDFWithOptionsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFWithOptions", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFWithOptions")
    @ResponseWrapper(localName = "RequestPDFWithOptionsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFWithOptionsResponse")
    public EnvelopePDF requestPDFWithOptions(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "PDFOptions", targetNamespace = "http://www.docusign.net/API/3.0")
        PDFOptions pdfOptions);

    /**
     * 
     * @param envelopeID
     * @param recipientName
     * @param recipientEmail
     * @param pdfOptions
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFRecipientsView", action = "http://www.docusign.net/API/3.0/RequestPDFRecipientsView")
    @WebResult(name = "RequestPDFRecipientsViewResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFRecipientsView", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFRecipientsView")
    @ResponseWrapper(localName = "RequestPDFRecipientsViewResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFRecipientsViewResponse")
    public EnvelopePDF requestPDFRecipientsView(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "RecipientName", targetNamespace = "http://www.docusign.net/API/3.0")
        String recipientName,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        String recipientEmail,
        @WebParam(name = "PDFOptions", targetNamespace = "http://www.docusign.net/API/3.0")
        PDFOptions pdfOptions);

    /**
     * 
     * @param envelopeID
     * @param pdFsOptions
     * @return
     *     returns com.docusign.hackathon.connect.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestPDFsWithOptions", action = "http://www.docusign.net/API/3.0/RequestPDFsWithOptions")
    @WebResult(name = "RequestPDFsWithOptionsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFsWithOptions", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFsWithOptions")
    @ResponseWrapper(localName = "RequestPDFsWithOptionsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFsWithOptionsResponse")
    public DocumentPDFs requestPDFsWithOptions(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "PDFsOptions", targetNamespace = "http://www.docusign.net/API/3.0")
        PDFsOptions pdFsOptions);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDF", action = "http://www.docusign.net/API/3.0/RequestPDF")
    @WebResult(name = "RequestPDFResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDF", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDF")
    @ResponseWrapper(localName = "RequestPDFResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFResponse")
    public EnvelopePDF requestPDF(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param addWaterMark
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFWithCert", action = "http://www.docusign.net/API/3.0/RequestPDFWithCert")
    @WebResult(name = "RequestPDFWithCertResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFWithCert", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFWithCert")
    @ResponseWrapper(localName = "RequestPDFWithCertResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestPDFWithCertResponse")
    public EnvelopePDF requestPDFWithCert(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "AddWaterMark", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean addWaterMark);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestCertificate", action = "http://www.docusign.net/API/3.0/RequestCertificate")
    @WebResult(name = "RequestCertificateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestCertificate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestCertificate")
    @ResponseWrapper(localName = "RequestCertificateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestCertificateResponse")
    public DocumentPDFs requestCertificate(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @param certLanguage
     * @return
     *     returns com.docusign.hackathon.connect.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestCertificateWithCertLanguage", action = "http://www.docusign.net/API/3.0/RequestCertificateWithCertLanguage")
    @WebResult(name = "RequestCertificateWithCertLanguageResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestCertificateWithCertLanguage", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestCertificateWithCertLanguage")
    @ResponseWrapper(localName = "RequestCertificateWithCertLanguageResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestCertificateWithCertLanguageResponse")
    public DocumentPDFs requestCertificateWithCertLanguage(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "CertLanguage", targetNamespace = "http://www.docusign.net/API/3.0")
        String certLanguage);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestDocumentPDFs", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFs")
    @WebResult(name = "RequestDocumentPDFsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFs", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestDocumentPDFs")
    @ResponseWrapper(localName = "RequestDocumentPDFsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestDocumentPDFsResponse")
    public DocumentPDFs requestDocumentPDFs(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestDocumentPDFsEx", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFsEx")
    @WebResult(name = "RequestDocumentPDFsExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFsEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestDocumentPDFsEx")
    @ResponseWrapper(localName = "RequestDocumentPDFsExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestDocumentPDFsExResponse")
    public DocumentPDFs requestDocumentPDFsEx(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @param recipientName
     * @param recipientEmail
     * @return
     *     returns com.docusign.hackathon.connect.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestDocumentPDFsRecipientsView", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFsRecipientsView")
    @WebResult(name = "RequestDocumentPDFsRecipientsViewResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFsRecipientsView", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestDocumentPDFsRecipientsView")
    @ResponseWrapper(localName = "RequestDocumentPDFsRecipientsViewResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestDocumentPDFsRecipientsViewResponse")
    public DocumentPDFs requestDocumentPDFsRecipientsView(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "RecipientName", targetNamespace = "http://www.docusign.net/API/3.0")
        String recipientName,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        String recipientEmail);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "RequestStatusEx", action = "http://www.docusign.net/API/3.0/RequestStatusEx")
    @WebResult(name = "RequestStatusExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusEx")
    @ResponseWrapper(localName = "RequestStatusExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusExResponse")
    public EnvelopeStatus requestStatusEx(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "RequestStatus", action = "http://www.docusign.net/API/3.0/RequestStatus")
    @WebResult(name = "RequestStatusResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatus", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatus")
    @ResponseWrapper(localName = "RequestStatusResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusResponse")
    public EnvelopeStatus requestStatus(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "RequestStatusWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestStatusWithDocumentFields")
    @WebResult(name = "RequestStatusWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusWithDocumentFields")
    @ResponseWrapper(localName = "RequestStatusWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusWithDocumentFieldsResponse")
    public EnvelopeStatus requestStatusWithDocumentFields(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeStatusFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.FilteredEnvelopeStatusChanges
     */
    @WebMethod(operationName = "RequestStatusCodes", action = "http://www.docusign.net/API/3.0/RequestStatusCodes")
    @WebResult(name = "RequestStatusCodesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusCodes", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusCodes")
    @ResponseWrapper(localName = "RequestStatusCodesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusCodesResponse")
    public FilteredEnvelopeStatusChanges requestStatusCodes(
        @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * 
     * @param envelopeStatusChangeFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.FilteredEnvelopeStatusChanges
     */
    @WebMethod(operationName = "RequestStatusChanges", action = "http://www.docusign.net/API/3.0/RequestStatusChanges")
    @WebResult(name = "RequestStatusChangesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusChanges", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusChanges")
    @ResponseWrapper(localName = "RequestStatusChangesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusChangesResponse")
    public FilteredEnvelopeStatusChanges requestStatusChanges(
        @WebParam(name = "EnvelopeStatusChangeFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeStatusChangeFilter envelopeStatusChangeFilter);

    /**
     * 
     * @param envelopeStatusFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.FilteredEnvelopeStatuses
     */
    @WebMethod(operationName = "RequestStatusesEx", action = "http://www.docusign.net/API/3.0/RequestStatusesEx")
    @WebResult(name = "RequestStatusesExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusesEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusesEx")
    @ResponseWrapper(localName = "RequestStatusesExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusesExResponse")
    public FilteredEnvelopeStatuses requestStatusesEx(
        @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * 
     * @param envelopeStatusFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.FilteredEnvelopeStatuses
     */
    @WebMethod(operationName = "RequestStatuses", action = "http://www.docusign.net/API/3.0/RequestStatuses")
    @WebResult(name = "RequestStatusesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatuses", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatuses")
    @ResponseWrapper(localName = "RequestStatusesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusesResponse")
    public FilteredEnvelopeStatuses requestStatuses(
        @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * 
     * @param envelopeStatusFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.FilteredEnvelopeStatuses
     */
    @WebMethod(operationName = "RequestStatusesWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestStatusesWithDocumentFields")
    @WebResult(name = "RequestStatusesWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusesWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusesWithDocumentFields")
    @ResponseWrapper(localName = "RequestStatusesWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestStatusesWithDocumentFieldsResponse")
    public FilteredEnvelopeStatuses requestStatusesWithDocumentFields(
        @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * 
     * @param senderEmail
     * @param userName
     * @param recipientEmail
     * @param senderAccountId
     * @return
     *     returns com.docusign.hackathon.connect.model.RecipientEsignList
     */
    @WebMethod(operationName = "GetRecipientEsignList", action = "http://www.docusign.net/API/3.0/GetRecipientEsignList")
    @WebResult(name = "GetRecipientEsignListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientEsignList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetRecipientEsignList")
    @ResponseWrapper(localName = "GetRecipientEsignListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetRecipientEsignListResponse")
    public RecipientEsignList getRecipientEsignList(
        @WebParam(name = "UserName", targetNamespace = "http://www.docusign.net/API/3.0")
        String userName,
        @WebParam(name = "SenderEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        String senderEmail,
        @WebParam(name = "SenderAccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String senderAccountId,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        String recipientEmail);

    /**
     * 
     * @param recipientEmail
     * @param senderAccountId
     * @return
     *     returns com.docusign.hackathon.connect.model.RecipientList
     */
    @WebMethod(operationName = "GetRecipientList", action = "http://www.docusign.net/API/3.0/GetRecipientList")
    @WebResult(name = "GetRecipientListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetRecipientList")
    @ResponseWrapper(localName = "GetRecipientListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetRecipientListResponse")
    public RecipientList getRecipientList(
        @WebParam(name = "SenderAccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String senderAccountId,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        String recipientEmail);

    /**
     * 
     * @param accountId
     * @param brandDeleteRequest
     * @return
     *     returns com.docusign.hackathon.connect.model.BrandResults
     */
    @WebMethod(operationName = "DeleteAccountBrands", action = "http://www.docusign.net/API/3.0/DeleteAccountBrands")
    @WebResult(name = "DeleteAccountBrandsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "DeleteAccountBrands", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.DeleteAccountBrands")
    @ResponseWrapper(localName = "DeleteAccountBrandsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.DeleteAccountBrandsResponse")
    public BrandResults deleteAccountBrands(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId,
        @WebParam(name = "BrandDeleteRequest", targetNamespace = "http://www.docusign.net/API/3.0")
        BrandDeleteRequest brandDeleteRequest);

    /**
     * 
     * @param accountId
     * @param brandDefinitions
     * @return
     *     returns com.docusign.hackathon.connect.model.BrandResults
     */
    @WebMethod(operationName = "CreateAccountBrands", action = "http://www.docusign.net/API/3.0/CreateAccountBrands")
    @WebResult(name = "CreateAccountBrandsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateAccountBrands", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateAccountBrands")
    @ResponseWrapper(localName = "CreateAccountBrandsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateAccountBrandsResponse")
    public BrandResults createAccountBrands(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId,
        @WebParam(name = "BrandDefinitions", targetNamespace = "http://www.docusign.net/API/3.0")
        BrandDefinitions brandDefinitions);

    /**
     * 
     * @param accountId
     * @return
     *     returns com.docusign.hackathon.connect.model.BrandResults
     */
    @WebMethod(operationName = "GetAccountBrands", action = "http://www.docusign.net/API/3.0/GetAccountBrands")
    @WebResult(name = "GetAccountBrandsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountBrands", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAccountBrands")
    @ResponseWrapper(localName = "GetAccountBrandsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAccountBrandsResponse")
    public BrandResults getAccountBrands(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId);

    /**
     * 
     * @param arg
     * @return
     *     returns com.docusign.hackathon.connect.model.AuthenticationStatus
     */
    @WebMethod(operationName = "GetRecipientAuthenticationStatusEx", action = "http://www.docusign.net/API/3.0/GetRecipientAuthenticationStatusEx")
    @WebResult(name = "GetRecipientAuthenticationStatusExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientAuthenticationStatusEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetRecipientAuthenticationStatusEx")
    @ResponseWrapper(localName = "GetRecipientAuthenticationStatusExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetRecipientAuthenticationStatusExResponse")
    public AuthenticationStatus getRecipientAuthenticationStatusEx(
        @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
        GetRecipientAuthenticationStatusExArg arg);

    /**
     * 
     * @param reason
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.VoidEnvelopeStatus
     */
    @WebMethod(operationName = "VoidEnvelope", action = "http://www.docusign.net/API/3.0/VoidEnvelope")
    @WebResult(name = "VoidEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "VoidEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.VoidEnvelope")
    @ResponseWrapper(localName = "VoidEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.VoidEnvelopeResponse")
    public VoidEnvelopeStatus voidEnvelope(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "Reason", targetNamespace = "http://www.docusign.net/API/3.0")
        String reason);

    /**
     * 
     * @param arg
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "MoveEnvelopes", action = "http://www.docusign.net/API/3.0/MoveEnvelopes")
    @WebResult(name = "MoveEnvelopesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "MoveEnvelopes", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.MoveEnvelopes")
    @ResponseWrapper(localName = "MoveEnvelopesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.MoveEnvelopesResponse")
    public boolean moveEnvelopes(
        @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
        MoveEnvelopesArg arg);

    /**
     * 
     * @param arg
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteEnvelopes", action = "http://www.docusign.net/API/3.0/DeleteEnvelopes")
    @WebResult(name = "DeleteEnvelopesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "DeleteEnvelopes", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.DeleteEnvelopes")
    @ResponseWrapper(localName = "DeleteEnvelopesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.DeleteEnvelopesResponse")
    public boolean deleteEnvelopes(
        @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
        DeleteEnvelopesArg arg);

    /**
     * 
     * @param accountId
     * @param arg
     * @return
     *     returns com.docusign.hackathon.connect.model.CaptiveRecipientResults
     */
    @WebMethod(operationName = "DeleteCaptiveRecipientsSignatures", action = "http://www.docusign.net/API/3.0/DeleteCaptiveRecipientsSignatures")
    @WebResult(name = "DeleteCaptiveRecipientsSignaturesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "DeleteCaptiveRecipientsSignatures", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.DeleteCaptiveRecipientsSignatures")
    @ResponseWrapper(localName = "DeleteCaptiveRecipientsSignaturesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.DeleteCaptiveRecipientsSignaturesResponse")
    public CaptiveRecipientResults deleteCaptiveRecipientsSignatures(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId,
        @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
        DeleteCaptiveRecipientsSignaturesArg arg);

    /**
     * 
     * @param clientUserID
     * @param envelopeID
     * @param authenticationAssertion
     * @param clientURLs
     * @param email
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestRecipientToken", action = "http://www.docusign.net/API/3.0/RequestRecipientToken")
    @WebResult(name = "RequestRecipientTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestRecipientToken")
    @ResponseWrapper(localName = "RequestRecipientTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestRecipientTokenResponse")
    public String requestRecipientToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
        String clientUserID,
        @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
        String username,
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
        String email,
        @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
        RequestRecipientTokenAuthenticationAssertion authenticationAssertion,
        @WebParam(name = "ClientURLs", targetNamespace = "http://www.docusign.net/API/3.0")
        RequestRecipientTokenClientURLs clientURLs);

    /**
     * 
     * @param clientUserID
     * @param envelopeID
     * @param authenticationAssertion
     * @param clientURLs
     * @param email
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestRecipientFaxToken", action = "http://www.docusign.net/API/3.0/RequestRecipientFaxToken")
    @WebResult(name = "RequestRecipientFaxTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientFaxToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestRecipientFaxToken")
    @ResponseWrapper(localName = "RequestRecipientFaxTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestRecipientFaxTokenResponse")
    public String requestRecipientFaxToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
        String clientUserID,
        @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
        String username,
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
        String email,
        @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
        RequestRecipientTokenAuthenticationAssertion authenticationAssertion,
        @WebParam(name = "ClientURLs", targetNamespace = "http://www.docusign.net/API/3.0")
        RequestRecipientTokenClientURLs clientURLs);

    /**
     * 
     * @param clientUserID
     * @param envelopeID
     * @param authenticationAssertion
     * @param email
     * @param username
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestRecipientFaxPDF", action = "http://www.docusign.net/API/3.0/RequestRecipientFaxPDF")
    @WebResult(name = "RequestRecipientFaxPDFResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientFaxPDF", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestRecipientFaxPDF")
    @ResponseWrapper(localName = "RequestRecipientFaxPDFResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestRecipientFaxPDFResponse")
    public EnvelopePDF requestRecipientFaxPDF(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
        String clientUserID,
        @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
        String username,
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
        String email,
        @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
        RequestRecipientTokenAuthenticationAssertion authenticationAssertion);

    /**
     * 
     * @param accountID
     * @param envelopeID
     * @param userID
     * @return
     *     returns com.docusign.hackathon.connect.model.TransferEnvelopeStatus
     */
    @WebMethod(operationName = "TransferEnvelope", action = "http://www.docusign.net/API/3.0/TransferEnvelope")
    @WebResult(name = "TransferEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "TransferEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.TransferEnvelope")
    @ResponseWrapper(localName = "TransferEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.TransferEnvelopeResponse")
    public TransferEnvelopeStatus transferEnvelope(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountID,
        @WebParam(name = "UserID", targetNamespace = "http://www.docusign.net/API/3.0")
        String userID);

    /**
     * 
     * @param accountId
     * @return
     *     returns com.docusign.hackathon.connect.model.AccountMembershipFeaturesList
     */
    @WebMethod(operationName = "GetAccountMembershipFeaturesList", action = "http://www.docusign.net/API/3.0/GetAccountMembershipFeaturesList")
    @WebResult(name = "GetAccountMembershipFeaturesListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountMembershipFeaturesList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAccountMembershipFeaturesList")
    @ResponseWrapper(localName = "GetAccountMembershipFeaturesListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAccountMembershipFeaturesListResponse")
    public AccountMembershipFeaturesList getAccountMembershipFeaturesList(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId);

    /**
     * 
     * @param accountId
     * @return
     *     returns com.docusign.hackathon.connect.model.AccountSettingsList
     */
    @WebMethod(operationName = "GetAccountSettingsList", action = "http://www.docusign.net/API/3.0/GetAccountSettingsList")
    @WebResult(name = "GetAccountSettingsListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountSettingsList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAccountSettingsList")
    @ResponseWrapper(localName = "GetAccountSettingsListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAccountSettingsListResponse")
    public AccountSettingsList getAccountSettingsList(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId);

    /**
     * 
     * @param envelopeId
     * @param externalId
     * @param transactionId
     * @return
     *     returns com.docusign.hackathon.connect.model.AuthoritativeCopyExportStatus
     */
    @WebMethod(operationName = "CompleteAuthoritativeCopyExport", action = "http://www.docusign.net/API/3.0/CompleteAuthoritativeCopyExport")
    @WebResult(name = "CompleteAuthoritativeCopyExportResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CompleteAuthoritativeCopyExport", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CompleteAuthoritativeCopyExport")
    @ResponseWrapper(localName = "CompleteAuthoritativeCopyExportResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CompleteAuthoritativeCopyExportResponse")
    public AuthoritativeCopyExportStatus completeAuthoritativeCopyExport(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId,
        @WebParam(name = "TransactionId", targetNamespace = "http://www.docusign.net/API/3.0")
        String transactionId,
        @WebParam(name = "ExternalId", targetNamespace = "http://www.docusign.net/API/3.0")
        String externalId);

    /**
     * 
     * @param envelopeId
     * @param checkSumHash
     * @param transactionId
     * @return
     *     returns com.docusign.hackathon.connect.model.AuthoritativeCopyExportStatus
     */
    @WebMethod(operationName = "GetAuthoritativeCopyExportKey", action = "http://www.docusign.net/API/3.0/GetAuthoritativeCopyExportKey")
    @WebResult(name = "GetAuthoritativeCopyExportKeyResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAuthoritativeCopyExportKey", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAuthoritativeCopyExportKey")
    @ResponseWrapper(localName = "GetAuthoritativeCopyExportKeyResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAuthoritativeCopyExportKeyResponse")
    public AuthoritativeCopyExportStatus getAuthoritativeCopyExportKey(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId,
        @WebParam(name = "TransactionId", targetNamespace = "http://www.docusign.net/API/3.0")
        String transactionId,
        @WebParam(name = "checkSumHash", targetNamespace = "http://www.docusign.net/API/3.0")
        byte[] checkSumHash);

    /**
     * 
     * @param envelopeId
     * @param checkSumHash
     * @param transactionId
     * @return
     *     returns com.docusign.hackathon.connect.model.AuthoritativeCopyExportStatus
     */
    @WebMethod(operationName = "AcknowledgeAuthoritativeCopyExport", action = "http://www.docusign.net/API/3.0/AcknowledgeAuthoritativeCopyExport")
    @WebResult(name = "AcknowledgeAuthoritativeCopyExportResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "AcknowledgeAuthoritativeCopyExport", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.AcknowledgeAuthoritativeCopyExport")
    @ResponseWrapper(localName = "AcknowledgeAuthoritativeCopyExportResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.AcknowledgeAuthoritativeCopyExportResponse")
    public AuthoritativeCopyExportStatus acknowledgeAuthoritativeCopyExport(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId,
        @WebParam(name = "TransactionId", targetNamespace = "http://www.docusign.net/API/3.0")
        String transactionId,
        @WebParam(name = "checkSumHash", targetNamespace = "http://www.docusign.net/API/3.0")
        byte[] checkSumHash);

    /**
     * 
     * @param envelopeId
     * @return
     *     returns com.docusign.hackathon.connect.model.AuthoritativeCopyExportDocuments
     */
    @WebMethod(operationName = "ExportAuthoritativeCopy", action = "http://www.docusign.net/API/3.0/ExportAuthoritativeCopy")
    @WebResult(name = "ExportAuthoritativeCopyResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "ExportAuthoritativeCopy", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.ExportAuthoritativeCopy")
    @ResponseWrapper(localName = "ExportAuthoritativeCopyResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.ExportAuthoritativeCopyResponse")
    public AuthoritativeCopyExportDocuments exportAuthoritativeCopy(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId);

    /**
     * 
     * @param envelopeId
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeAuditEventsResponse.EnvelopeAuditEventsResult
     */
    @WebMethod(operationName = "EnvelopeAuditEvents", action = "http://www.docusign.net/API/3.0/EnvelopeAuditEvents")
    @WebResult(name = "EnvelopeAuditEventsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "EnvelopeAuditEvents", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.EnvelopeAuditEvents")
    @ResponseWrapper(localName = "EnvelopeAuditEventsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.EnvelopeAuditEventsResponse")
    public com.docusign.hackathon.connect.model.EnvelopeAuditEventsResponse.EnvelopeAuditEventsResult envelopeAuditEvents(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId);

    /**
     * 
     * @param envelopeId
     * @return
     *     returns com.docusign.hackathon.connect.model.ArrayOfEnvelopeAuditEvent
     */
    @WebMethod(operationName = "EnvelopeAuditEventsV2", action = "http://www.docusign.net/API/3.0/EnvelopeAuditEventsV2")
    @WebResult(name = "EnvelopeAuditEventsV2Result", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "EnvelopeAuditEventsV2", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.EnvelopeAuditEventsV2")
    @ResponseWrapper(localName = "EnvelopeAuditEventsV2Response", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.EnvelopeAuditEventsV2Response")
    public ArrayOfEnvelopeAuditEvent envelopeAuditEventsV2(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeId);

    /**
     * 
     * @param arg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestEnvelopeHistoryToken", action = "http://www.docusign.net/API/3.0/RequestEnvelopeHistoryToken")
    @WebResult(name = "RequestEnvelopeHistoryTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestEnvelopeHistoryToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestEnvelopeHistoryToken")
    @ResponseWrapper(localName = "RequestEnvelopeHistoryTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestEnvelopeHistoryTokenResponse")
    public String requestEnvelopeHistoryToken(
        @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
        RequestEnvelopeHistoryTokenArg arg);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Ping", action = "http://www.docusign.net/API/3.0/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PingResponse")
    public boolean ping();

    /**
     * 
     * @param templateReferences
     * @param recipients
     * @param envelopeInformation
     * @param activateEnvelope
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateEnvelopeFromTemplates", action = "http://www.docusign.net/API/3.0/CreateEnvelopeFromTemplates")
    @WebResult(name = "CreateEnvelopeFromTemplatesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelopeFromTemplates", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateEnvelopeFromTemplates")
    @ResponseWrapper(localName = "CreateEnvelopeFromTemplatesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateEnvelopeFromTemplatesResponse")
    public EnvelopeStatus createEnvelopeFromTemplates(
        @WebParam(name = "TemplateReferences", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfTemplateReference templateReferences,
        @WebParam(name = "Recipients", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfRecipient1 recipients,
        @WebParam(name = "EnvelopeInformation", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeInformation envelopeInformation,
        @WebParam(name = "ActivateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean activateEnvelope);

    /**
     * 
     * @param compositeTemplates
     * @param envelopeInformation
     * @param activateEnvelope
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateEnvelopeFromTemplatesAndForms", action = "http://www.docusign.net/API/3.0/CreateEnvelopeFromTemplatesAndForms")
    @WebResult(name = "CreateEnvelopeFromTemplatesAndFormsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelopeFromTemplatesAndForms", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateEnvelopeFromTemplatesAndForms")
    @ResponseWrapper(localName = "CreateEnvelopeFromTemplatesAndFormsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.CreateEnvelopeFromTemplatesAndFormsResponse")
    public EnvelopeStatus createEnvelopeFromTemplatesAndForms(
        @WebParam(name = "EnvelopeInformation", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeInformation envelopeInformation,
        @WebParam(name = "CompositeTemplates", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfCompositeTemplate compositeTemplates,
        @WebParam(name = "ActivateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean activateEnvelope);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.DocuSignEnvelopeInformation
     */
    @WebMethod(operationName = "GetStatusInDocuSignConnectFormat", action = "http://www.docusign.net/API/3.0/GetStatusInDocuSignConnectFormat")
    @WebResult(name = "GetStatusInDocuSignConnectFormatResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetStatusInDocuSignConnectFormat", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetStatusInDocuSignConnectFormat")
    @ResponseWrapper(localName = "GetStatusInDocuSignConnectFormatResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetStatusInDocuSignConnectFormatResponse")
    public DocuSignEnvelopeInformation getStatusInDocuSignConnectFormat(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.PurgeDocumentStatus
     */
    @WebMethod(operationName = "PurgeDocuments", action = "http://www.docusign.net/API/3.0/PurgeDocuments")
    @WebResult(name = "PurgeDocumentsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "PurgeDocuments", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PurgeDocuments")
    @ResponseWrapper(localName = "PurgeDocumentsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PurgeDocumentsResponse")
    public PurgeDocumentStatus purgeDocuments(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeID
     * @return
     *     returns com.docusign.hackathon.connect.model.PurgeDocumentStatus
     */
    @WebMethod(operationName = "PurgeDocumentsAndMetaData", action = "http://www.docusign.net/API/3.0/PurgeDocumentsAndMetaData")
    @WebResult(name = "PurgeDocumentsAndMetaDataResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "PurgeDocumentsAndMetaData", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PurgeDocumentsAndMetaData")
    @ResponseWrapper(localName = "PurgeDocumentsAndMetaDataResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PurgeDocumentsAndMetaDataResponse")
    public PurgeDocumentStatus purgeDocumentsAndMetaData(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID);

    /**
     * 
     * @param envelopeTemplate
     * @return
     *     returns com.docusign.hackathon.connect.model.SaveTemplateResult
     */
    @WebMethod(operationName = "SaveTemplate", action = "http://www.docusign.net/API/3.0/SaveTemplate")
    @WebResult(name = "SaveTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SaveTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SaveTemplate")
    @ResponseWrapper(localName = "SaveTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SaveTemplateResponse")
    public SaveTemplateResult saveTemplate(
        @WebParam(name = "EnvelopeTemplate", targetNamespace = "http://www.docusign.net/API/3.0")
        EnvelopeTemplate envelopeTemplate);

    /**
     * 
     * @param accountID
     * @param shared
     * @param templateXML
     * @return
     *     returns com.docusign.hackathon.connect.model.SaveTemplateResult
     */
    @WebMethod(operationName = "UploadTemplate", action = "http://www.docusign.net/API/3.0/UploadTemplate")
    @WebResult(name = "UploadTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "UploadTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.UploadTemplate")
    @ResponseWrapper(localName = "UploadTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.UploadTemplateResponse")
    public SaveTemplateResult uploadTemplate(
        @WebParam(name = "TemplateXML", targetNamespace = "http://www.docusign.net/API/3.0")
        String templateXML,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountID,
        @WebParam(name = "Shared", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean shared);

    /**
     * 
     * @param accountID
     * @param includeAdvancedTemplates
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeTemplates
     */
    @WebMethod(operationName = "RequestTemplates", action = "http://www.docusign.net/API/3.0/RequestTemplates")
    @WebResult(name = "RequestTemplatesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplates", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplates")
    @ResponseWrapper(localName = "RequestTemplatesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplatesResponse")
    public EnvelopeTemplates requestTemplates(
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountID,
        @WebParam(name = "IncludeAdvancedTemplates", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeAdvancedTemplates);

    /**
     * 
     * @param templateID
     * @param includeDocumentBytes
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplate", action = "http://www.docusign.net/API/3.0/RequestTemplate")
    @WebResult(name = "RequestTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplate")
    @ResponseWrapper(localName = "RequestTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateResponse")
    public EnvelopeTemplate requestTemplate(
        @WebParam(name = "TemplateID", targetNamespace = "http://www.docusign.net/API/3.0")
        String templateID,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes);

    /**
     * 
     * @param templateIDs
     * @param includeDocumentBytes
     * @return
     *     returns com.docusign.hackathon.connect.model.ArrayOfEnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplateList", action = "http://www.docusign.net/API/3.0/RequestTemplateList")
    @WebResult(name = "RequestTemplateListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplateList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateList")
    @ResponseWrapper(localName = "RequestTemplateListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateListResponse")
    public ArrayOfEnvelopeTemplate requestTemplateList(
        @WebParam(name = "TemplateIDs", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfString5 templateIDs,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes);

    /**
     * 
     * @param templateID
     * @param includeDocumentBytes
     * @return
     *     returns com.docusign.hackathon.connect.model.EnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplateWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestTemplateWithDocumentFields")
    @WebResult(name = "RequestTemplateWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplateWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateWithDocumentFields")
    @ResponseWrapper(localName = "RequestTemplateWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateWithDocumentFieldsResponse")
    public EnvelopeTemplate requestTemplateWithDocumentFields(
        @WebParam(name = "TemplateID", targetNamespace = "http://www.docusign.net/API/3.0")
        String templateID,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes);

    /**
     * 
     * @param templateIDs
     * @param includeDocumentBytes
     * @return
     *     returns com.docusign.hackathon.connect.model.ArrayOfEnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplateListWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestTemplateListWithDocumentFields")
    @WebResult(name = "RequestTemplateListWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplateListWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateListWithDocumentFields")
    @ResponseWrapper(localName = "RequestTemplateListWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestTemplateListWithDocumentFieldsResponse")
    public ArrayOfEnvelopeTemplate requestTemplateListWithDocumentFields(
        @WebParam(name = "TemplateIDs", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfString5 templateIDs,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes);

    /**
     * 
     * @param goToEnvelopeID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAuthenticationToken", action = "http://www.docusign.net/API/3.0/GetAuthenticationToken")
    @WebResult(name = "GetAuthenticationTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAuthenticationToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAuthenticationToken")
    @ResponseWrapper(localName = "GetAuthenticationTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAuthenticationTokenResponse")
    public String getAuthenticationToken(
        @WebParam(name = "GoToEnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String goToEnvelopeID);

    /**
     * 
     * @param accountID
     * @return
     *     returns com.docusign.hackathon.connect.model.ArrayOfAddressBookItem
     */
    @WebMethod(operationName = "GetAddressBookItems", action = "http://www.docusign.net/API/3.0/GetAddressBookItems")
    @WebResult(name = "GetAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAddressBookItems")
    @ResponseWrapper(localName = "GetAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetAddressBookItemsResponse")
    public ArrayOfAddressBookItem getAddressBookItems(
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountID);

    /**
     * 
     * @param addressBookItems
     * @param returnAddressBook
     * @return
     *     returns com.docusign.hackathon.connect.model.UpdateAddressBookResult
     */
    @WebMethod(operationName = "UpdateAddressBookItems", action = "http://www.docusign.net/API/3.0/UpdateAddressBookItems")
    @WebResult(name = "UpdateAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "UpdateAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.UpdateAddressBookItems")
    @ResponseWrapper(localName = "UpdateAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.UpdateAddressBookItemsResponse")
    public UpdateAddressBookResult updateAddressBookItems(
        @WebParam(name = "AddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfAddressBookItem addressBookItems,
        @WebParam(name = "ReturnAddressBook", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean returnAddressBook);

    /**
     * 
     * @param addressBookRemoveItems
     * @param returnAddressBook
     * @return
     *     returns com.docusign.hackathon.connect.model.UpdateAddressBookResult
     */
    @WebMethod(operationName = "RemoveAddressBookItems", action = "http://www.docusign.net/API/3.0/RemoveAddressBookItems")
    @WebResult(name = "RemoveAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RemoveAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RemoveAddressBookItems")
    @ResponseWrapper(localName = "RemoveAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RemoveAddressBookItemsResponse")
    public UpdateAddressBookResult removeAddressBookItems(
        @WebParam(name = "AddressBookRemoveItems", targetNamespace = "http://www.docusign.net/API/3.0")
        ArrayOfAddressBookRemoveItem addressBookRemoveItems,
        @WebParam(name = "ReturnAddressBook", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean returnAddressBook);

    /**
     * 
     * @param accountID
     * @param block
     * @param transactionID
     * @return
     *     returns com.docusign.hackathon.connect.model.SynchEnvelopeStatus
     */
    @WebMethod(operationName = "SynchEnvelope", action = "http://www.docusign.net/API/3.0/SynchEnvelope")
    @WebResult(name = "SynchEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SynchEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SynchEnvelope")
    @ResponseWrapper(localName = "SynchEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SynchEnvelopeResponse")
    public SynchEnvelopeStatus synchEnvelope(
        @WebParam(name = "TransactionID", targetNamespace = "http://www.docusign.net/API/3.0")
        String transactionID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountID,
        @WebParam(name = "Block", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean block);

    /**
     * 
     * @param accountID
     * @param envelopeID
     * @param returnURL
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSenderToken", action = "http://www.docusign.net/API/3.0/RequestSenderToken")
    @WebResult(name = "RequestSenderTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestSenderToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestSenderToken")
    @ResponseWrapper(localName = "RequestSenderTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestSenderTokenResponse")
    public String requestSenderToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountID,
        @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/3.0")
        String returnURL);

    /**
     * 
     * @param envelopeID
     * @param suppressNavigation
     * @param returnURL
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestCorrectToken", action = "http://www.docusign.net/API/3.0/RequestCorrectToken")
    @WebResult(name = "RequestCorrectTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestCorrectToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestCorrectToken")
    @ResponseWrapper(localName = "RequestCorrectTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestCorrectTokenResponse")
    public String requestCorrectToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "SuppressNavigation", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean suppressNavigation,
        @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/3.0")
        String returnURL);

    /**
     * 
     * @param folderFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.FolderResults
     */
    @WebMethod(operationName = "GetFolderItems", action = "http://www.docusign.net/API/3.0/GetFolderItems")
    @WebResult(name = "GetFolderItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetFolderItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetFolderItems")
    @ResponseWrapper(localName = "GetFolderItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetFolderItemsResponse")
    public FolderResults getFolderItems(
        @WebParam(name = "FolderFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        FolderFilter folderFilter);

    /**
     * 
     * @param foldersFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.AvailableFolders
     */
    @WebMethod(operationName = "GetFolderList", action = "http://www.docusign.net/API/3.0/GetFolderList")
    @WebResult(name = "GetFolderListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetFolderList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetFolderList")
    @ResponseWrapper(localName = "GetFolderListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetFolderListResponse")
    public AvailableFolders getFolderList(
        @WebParam(name = "FoldersFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        FoldersFilter foldersFilter);

    /**
     * 
     * @param envelopeID
     * @param includeDocumentBytes
     * @return
     *     returns com.docusign.hackathon.connect.model.Envelope
     */
    @WebMethod(operationName = "RequestEnvelope", action = "http://www.docusign.net/API/3.0/RequestEnvelope")
    @WebResult(name = "RequestEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestEnvelope")
    @ResponseWrapper(localName = "RequestEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestEnvelopeResponse")
    public Envelope requestEnvelope(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes);

    /**
     * 
     * @param envelopeID
     * @param includeDocumentBytes
     * @return
     *     returns com.docusign.hackathon.connect.model.Envelope
     */
    @WebMethod(operationName = "RequestEnvelopeWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestEnvelopeWithDocumentFields")
    @WebResult(name = "RequestEnvelopeWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestEnvelopeWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestEnvelopeWithDocumentFields")
    @ResponseWrapper(localName = "RequestEnvelopeWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.RequestEnvelopeWithDocumentFieldsResponse")
    public Envelope requestEnvelopeWithDocumentFields(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        String envelopeID,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes);

    /**
     * 
     * @param connectFailuresFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.ArrayOfConnectFailure
     */
    @WebMethod(operationName = "GetConnectFailures", action = "http://www.docusign.net/API/3.0/GetConnectFailures")
    @WebResult(name = "GetConnectFailuresResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetConnectFailures", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetConnectFailures")
    @ResponseWrapper(localName = "GetConnectFailuresResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetConnectFailuresResponse")
    public ArrayOfConnectFailure getConnectFailures(
        @WebParam(name = "ConnectFailuresFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        ConnectFailuresFilter connectFailuresFilter);

    /**
     * 
     * @param publishConnectFailuresFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.ArrayOfPublishConnectFailuresResult
     */
    @WebMethod(operationName = "PublishConnectFailures", action = "http://www.docusign.net/API/3.0/PublishConnectFailures")
    @WebResult(name = "PublishConnectFailuresResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "PublishConnectFailures", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PublishConnectFailures")
    @ResponseWrapper(localName = "PublishConnectFailuresResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.PublishConnectFailuresResponse")
    public ArrayOfPublishConnectFailuresResult publishConnectFailures(
        @WebParam(name = "PublishConnectFailuresFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        PublishConnectFailuresFilter publishConnectFailuresFilter);

    /**
     * 
     * @param accountId
     * @param sharedAccessFilter
     * @return
     *     returns com.docusign.hackathon.connect.model.GetSharedAccessResult
     */
    @WebMethod(operationName = "GetSharedAccess", action = "http://www.docusign.net/API/3.0/GetSharedAccess")
    @WebResult(name = "GetSharedAccessResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetSharedAccess", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetSharedAccess")
    @ResponseWrapper(localName = "GetSharedAccessResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.GetSharedAccessResponse")
    public GetSharedAccessResult getSharedAccess(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        String accountId,
        @WebParam(name = "SharedAccessFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        SharedAccessFilter sharedAccessFilter);

    /**
     * 
     * @param setSharedAccessRequest
     * @return
     *     returns com.docusign.hackathon.connect.model.SetSharedAccessResult
     */
    @WebMethod(operationName = "SetSharedAccess", action = "http://www.docusign.net/API/3.0/SetSharedAccess")
    @WebResult(name = "SetSharedAccessResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SetSharedAccess", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SetSharedAccess")
    @ResponseWrapper(localName = "SetSharedAccessResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.hackathon.connect.model.SetSharedAccessResponse")
    public SetSharedAccessResult setSharedAccess(
        @WebParam(name = "SetSharedAccessRequest", targetNamespace = "http://www.docusign.net/API/3.0")
        SetSharedAccessRequest setSharedAccessRequest);

}
